<?php
/**
 * Difengo signin form template
 *
 * @see \Difengo\Login\Block\Form\SignIn
 * @var $block \Difengo\Login\Block\Form\SignIn
 */
?>

<form class="form"
    action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
    id="difengo-form"
    method="post" 
    data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
    data-mage-init='{"validation":{}}'>

<fieldset class="fieldset">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Difengo Login') ?></span></legend><br>
    <div class="field required">
        <label for="difengo_token" class="label">
            <span><?php /* @escapeNotVerified */ echo __('Token') ?></span>
        </label>

        <div class="control">
            <input type="text" 
                    data-validate="{required:true, minlength:13, maxlength:13}"
                    id="difengo_token"
                    name="difengo_token"
                    class="input-text" />
        </div>
    </div>
</fieldset>
<div id="message-container"></div>
<div class="actions-toolbar">
    <div class="primary">
        <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
            <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
        </button>
    </div>
</div>

</form>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#difengo-form');
        dataForm.mage('validation', {
            errorPlacement: function(error, element) {
                error.appendTo('#message-container');
            },
        });
    });
</script>